# Generated by Django 4.0.4 on 2022-07-27 18:50

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('preferred_name', models.CharField(max_length=50)),
                ('max_guests', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('is_rehearsal_guest', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coming', models.BooleanField()),
                ('num_guests', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RSVP',
                'verbose_name_plural': 'RSVPs',
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.CharField(blank=True, choices=[('celery', 'Celery / Sellerie'), ('gluten', 'Gluten'), ('crustaceans', 'Crustaceans / Krebstiere'), ('eggs', 'Eggs / Eier'), ('fish', 'Fish / Fisch'), ('lupin', 'Lupin / Lupine'), ('milk', 'Milk / Milch'), ('molluscs', 'Molluscs / Weichtiere'), ('mustard', 'Mustard / Senf'), ('peanuts', 'Peanuts / Erdnüsse'), ('sesame', 'Sesame / Sesam'), ('soybeans', 'Soy beans / Soja'), ('sulphur', 'Sulphur dioxide / Schwefeldioxid'), ('nuts', 'Tree nuts / Schalenfrüchte (Nüsse)')], max_length=30, null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Allergies',
            },
        ),
        migrations.CreateModel(
            name='AllergySummary',
            fields=[
            ],
            options={
                'verbose_name': 'Allergy Summary',
                'verbose_name_plural': 'Allergies Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wedding.allergy',),
        ),
        migrations.CreateModel(
            name='RsvpSummary',
            fields=[
            ],
            options={
                'verbose_name': 'RSVP Summary',
                'verbose_name_plural': 'RSVPs Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wedding.rsvp',),
        ),
    ]
