# Generated by Django 4.0.4 on 2022-06-04 12:40

from django.db import migrations, models
import django.db.models.deletion
import wedding.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('invite_code', models.CharField(default=wedding.utils.invite_code_generator, max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_guests', models.IntegerField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.CharField(choices=[('celery', 'Celery / Sellerie'), ('gluten', 'Gluten'), ('crustaceans', 'Crustaceans / Krebstiere'), ('eggs', 'Eggs / Eier'), ('fish', 'Fish / Fisch'), ('lupin', 'Lupin / Lupine'), ('milk', 'Milk / Milch'), ('molluscs', 'Molluscs / Weichtiere'), ('mustard', 'Mustard / Senf'), ('peanuts', 'Peanuts / Erdnüsse'), ('sesame', 'Sesame / Sesam'), ('soybeans', 'Soy beans / Soja'), ('sulphur', 'Sulphur dioxide / Schwefeldioxid'), ('nuts', 'Tree nuts / Schalenfrüchte (Nüsse)')], max_length=30)),
                ('note', models.CharField(max_length=200)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.guest')),
            ],
        ),
    ]
