# Generated by Django 4.0.4 on 2022-06-04 10:16

from django.db import migrations, models
import wedding.utils


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default=wedding.utils.invite_code_generator, max_length=6),
        ),
    ]
