# Generated by Django 4.0.4 on 2023-01-07 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='num_guests',
        ),
        migrations.AlterField(
            model_name='allergy',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.guest'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.guest'),
        ),
    ]
