# Generated by Django 4.0.4 on 2022-06-04 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_alter_user_invite_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Guest',
        ),
        migrations.RenameField(
            model_name='allergy',
            old_name='user',
            new_name='guest',
        ),
        migrations.RenameField(
            model_name='rsvp',
            old_name='user',
            new_name='guest',
        ),
        migrations.RenameField(
            model_name='rsvp',
            old_name='guests',
            new_name='num_guests',
        ),
    ]
