# Generated by Django 4.0.4 on 2022-06-04 11:56

from django.db import migrations, models
import wedding.utils


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_rename_user_guest_rename_user_allergy_guest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='invite_code',
            field=models.CharField(default=wedding.utils.invite_code_generator, max_length=6, unique=True),
        ),
    ]
