# Generated by Django 4.0.4 on 2023-01-07 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_remove_rsvp_num_guests_alter_allergy_guest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergy',
            name='guest',
        ),
        migrations.DeleteModel(
            name='AllergySummary',
        ),
        migrations.DeleteModel(
            name='Allergy',
        ),
    ]
