# Generated by Django 4.0.4 on 2023-01-07 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0005_rsvp_first_course_rsvp_second_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='preferred_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_name',
        ),
    ]
