# Generated by Django 4.0.4 on 2023-01-07 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0006_rename_preferred_name_guest_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='max_guests',
        ),
    ]
