# Generated by Django 4.0.4 on 2023-02-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0007_remove_user_max_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='first_course',
            field=models.CharField(choices=[('cheese-salad', 'Summer salad with berries and goat cheese'), ('salmon-salad', 'Salad with Loch Fyne Braden smoked salmon')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='second_course',
            field=models.CharField(choices=[('beef', 'Slow Braised Feather Blade of Beef'), ('salmon', 'Poached Fillet of Tay Salmon'), ('risotto', 'Asparagus and Mushroom Risotto')], max_length=50),
        ),
    ]
