# Generated by Django 4.0.4 on 2023-02-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0008_alter_rsvp_first_course_alter_rsvp_second_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='first_course',
            field=models.CharField(choices=[('cheese-salad', 'Summer salad with berries and goat cheese / Sommersalat mit Beeren und Ziegenkäse'), ('salmon-salad', 'Salad with Loch Fyne Braden smoked salmon / Salat mit Loch Fyne Braden Räucherlachs')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='second_course',
            field=models.CharField(choices=[('beef', 'Slow Braised Feather Blade of Beef / Langsam geschmorte Federklinge vom Rind'), ('salmon', 'Poached Fillet of Tay Salmon / Pochiertes Filet vom Tay-Lachs'), ('risotto', 'Asparagus and Mushroom Risotto / Risotto mit Spargel und Pilzen')], max_length=50),
        ),
    ]
