# Generated by Django 4.0.4 on 2023-02-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0010_alter_user_options_alter_user_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together={('primary_guest', 'name')},
        ),
    ]
