# Generated by Django 4.0.4 on 2023-05-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0013_alter_rsvp_first_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='first_course',
            field=models.CharField(choices=[('soup', 'Butternut Squash and Sweet Potato Soup / Butternusskürbis- und Süßkartoffelsuppe'), ('salmon-salad', 'Salad with Loch Fyne Braden smoked salmon / Salat mit Loch Fyne Braden Räucherlachs')], max_length=50),
        ),
    ]
